DO $$
BEGIN
    -- 1. Create Missing Tables if they don't exist
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'salvadanai') THEN
        CREATE TABLE salvadanai (
            id_salvadanaio SERIAL PRIMARY KEY,
            id_famiglia integer NOT NULL, -- Logical FK to Famiglie
            id_conto integer NULL, -- Logical FK to Conti
            nome text NOT NULL,
            importo_assegnato text NOT NULL,
            incide_su_liquidita boolean DEFAULT false,
            note text,
            data_creazione TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            id_conto_condiviso integer NULL, -- Logical FK to ContiCondivisi
            usa_saldo_totale boolean DEFAULT false
        );
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'obiettivi_risparmio') THEN
        CREATE TABLE obiettivi_risparmio (
            id SERIAL PRIMARY KEY,
            id_famiglia integer, -- Logical FK
            nome text NOT NULL,
            importo_obiettivo text NOT NULL,
            data_obiettivo date NOT NULL,
            note text,
            data_creazione TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            mostra_suggerimento_mensile boolean DEFAULT true
        );
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'storicoassetglobale') THEN
        CREATE TABLE storicoassetglobale (
            id SERIAL PRIMARY KEY,
            ticker TEXT NOT NULL,
            data date NOT NULL,
            prezzo_chiusura numeric NOT NULL,
            data_aggiornamento TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );
    END IF;

    -- 2. Add Missing Columns (Generated by compare_schemas.py)
    -- inviti.chiave_famiglia_criptata
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='inviti' AND column_name='chiave_famiglia_criptata') THEN
        ALTER TABLE inviti ADD COLUMN chiave_famiglia_criptata text;
    END IF;

    -- appartenenza_famiglia.nome_visualizzato_criptato
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='appartenenza_famiglia' AND column_name='nome_visualizzato_criptato') THEN
        ALTER TABLE appartenenza_famiglia ADD COLUMN nome_visualizzato_criptato text;
    END IF;

    -- transazioni.importo_nascosto (Assuming boolean)
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='transazioni' AND column_name='importo_nascosto') THEN
        ALTER TABLE transazioni ADD COLUMN importo_nascosto boolean DEFAULT FALSE;
    END IF;

    -- spesefisse columns
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='spesefisse' AND column_name='id_carta') THEN
        ALTER TABLE spesefisse ADD COLUMN id_carta integer;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='spesefisse' AND column_name='is_giroconto') THEN
        ALTER TABLE spesefisse ADD COLUMN is_giroconto boolean DEFAULT FALSE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='spesefisse' AND column_name='id_conto_personale_beneficiario') THEN
        ALTER TABLE spesefisse ADD COLUMN id_conto_personale_beneficiario integer;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='spesefisse' AND column_name='id_conto_condiviso_beneficiario') THEN
        ALTER TABLE spesefisse ADD COLUMN id_conto_condiviso_beneficiario integer;
    END IF;

END $$;
