# Contiene le stringhe per l'internazionalizzazione (i18n)
STRINGS = {
    "it": {
        # Generali
        "app_title": "Budget Familiare",
        "edit": "Modifica",
        "delete": "Elimina",
        "save": "Salva",
        "cancel": "Annulla",
        "close": "Chiudi",
        "add": "Aggiungi",
        "new_transaction": "Nuova Transazione",
        "new_transfer": "Nuovo Giroconto",
        "no_category": "Nessuna Categoria",
        "confirm_delete_title": "Conferma Eliminazione",
        "confirm_delete_content": "Sei sicuro di voler eliminare questo elemento? L'azione è irreversibile.",
        "yes_delete": "Sì, Elimina",
        "fill_all_fields": "Compila tutti i campi obbligatori.",
        "invalid_amount": "Importo non valido.",
        "amount_not_zero": "L'importo non può essere zero.",
        "description_required": "Descrizione obbligatoria.",
        "error_dialog_title": "Errore",
        "select_an_account": "Seleziona un conto.",

        # Schede Principali
        "my_data": "I Miei Dati",
        "budget": "Budget",
        "personal_accounts": "Conti Personali",
        "shared_accounts": "Conti Condivisi",
        "fixed_expenses": "Spese Fisse",
        "loans": "Prestiti",
        "properties": "Immobili",
        "family": "Famiglia",

        # Azioni AppBar
        "settings": "Impostazioni",
        "admin_panel_title": "Pannello Admin",
        "export_data": "Esporta Dati",
        "logout": "Logout",
        "info": "Informazioni",

        # Recupero Password
        "forgot_password": "Password dimenticata?",
        "password_recovery_title": "Recupero Password",
        "password_recovery_desc": "Inserisci la tua email per ricevere una password temporanea.",
        "send_reset_link": "Invia Password Temporanea",
        "back_to_login": "Torna al Login",
        "email_is_required": "L'email è obbligatoria.",
        "set_new_password_title": "Crea una Nuova Password",
        "new_password": "Nuova Password",
        "confirm_new_password": "Conferma Nuova Password",
        "save_new_password": "Salva Nuova Password",
        "passwords_do_not_match": "Le password non coincidono o sono vuote.",
        "password_updated_success": "Password aggiornata con successo! Ora puoi effettuare il login.",
        "invalid_or_expired_token": "Token non valido o scaduto. Richiedi un nuovo reset.",
        "reset_link_sent_confirmation": "Se esiste un account associato a questa email, è stata inviata una password temporanea.",
        "no_account_question": "Non hai un account?",
        "register_now": "Registrati",

        # Pannello Admin
        "categories_management": "Gestione Categorie",
        "subcategory": "Sottocategoria",
        "members_management": "Gestione Membri",
        "admin_google_settings": "Google",
        "add_category": "Aggiungi Categoria",
        "add_subcategory": "Aggiungi Sottocategoria",
        "category_name": "Nome Categoria",
        "subcategory_name": "Nome Sottocategoria",
        "no_categories_found": "Nessuna categoria trovata.",
        "invite_member": "Invita Membro",
        "username_or_email": "Username o Email",
        "role": "Ruolo",
        "edit_role_for": "Modifica ruolo per",
        "username": "Username",
        "email": "Email",
        "invite": "Invita",
        "remove_from_family": "Rimuovi dalla famiglia",
        "no_members_found": "Nessun altro membro nella famiglia.",

        # Dialogo Transazioni
        "expense": "Spesa",
        "income": "Incasso",
        "category_optional": "Categoria (opzionale)",
        "shared_suffix": "(Condiviso)",
        "personal_suffix": "(Personale)",

        # Dialogo Conti
        "manage_account": "Gestisci Conto",
        "add_account": "Aggiungi Conto",
        "edit_account": "Modifica Conto",
        "account_name_placeholder": "Nome Conto (es. Conto Principale)",
        "account_type": "Tipo di Conto",
        "iban_optional": "IBAN (Opzionale)",
        "initial_balance_optional": "Saldo Iniziale (Opzionale)",
        "set_initial_balance": "Imposta Saldo Iniziale",
        "add_initial_asset": "Aggiungi Asset Iniziale",
        "initial_assets": "Asset Iniziali:",
        "initial_assets_desc": "Inserisci il valore attuale e il G/L totale pre-esistente (opzionale).",
        "ticker": "Ticker",
        "asset_name": "Nome Asset",
        "quantity": "Quantità",
        "current_unit_price": "Px Attuale Unit.",
        "past_gain_loss": "G/L Tot. Pregresso",
        "remove_asset": "Rimuovi Asset",
        "set_as_default_account": "Imposta come conto predefinito per le spese",
        "iban_in_use_or_invalid": "IBAN già in uso o non valido",
        "avg_purchase_price": "Prezzo Medio di Acquisto",
        "avg_purchase_price_tooltip": "Prezzo medio ponderato di acquisto degli asset",
        "past_gain_loss_tooltip": "Gain/Loss totale pregresso (prima dell'inserimento nel sistema)",

        # Dialogo Conti Condivisi
        "manage_shared_account_dialog": "Gestisci Conto Condiviso",
        "create_shared_account": "Crea Conto Condiviso",
        "edit_shared_account": "Modifica Conto Condiviso",
        "shared_account_name": "Nome Conto Condiviso",
        "sharing_type": "Tipo di Condivisione",
        "sharing_type_family": "Tutta la Famiglia (gestito da Admin)",
        "sharing_type_users": "Utenti Specifici",
        "select_participants": "Seleziona Partecipanti (solo per 'Utenti Specifici'):",
        "select_at_least_one_participant": "Seleziona almeno un partecipante per i conti 'Utenti Specifici'.",

        # Dialogo Giroconto
        "new_transfer_dialog": "Nuovo Giroconto",
        "from_account": "Da Conto (Sorgente)",
        "to_account": "A Conto (Destinazione)",
        "transfer_description_placeholder": "Descrizione (es. Spese comuni)",
        "accounts_must_be_different": "I conti devono essere diversi",
        "select_source_account": "Seleziona un conto di origine",
        "select_destination_account": "Seleziona un conto di destinazione",
        "execute_transfer": "Esegui Giroconto",

        # Dialogo Spese Fisse
        "manage_fixed_expense": "Gestisci Spesa Fissa",
        "add_fixed_expense": "Aggiungi Spesa Fissa",
        "edit_fixed_expense": "Modifica Spesa Fissa",
        "expense_name_placeholder": "Nome Spesa (es. Abbonamento Netflix)",
        "debit_account": "Conto di Addebito",
        "debit_day": "Giorno del Mese per l'Addebito",

        # Dialogo Fondo Pensione
        "manage_pension_fund_dialog": "Gestione Fondo Pensione",
        "manage_pension_fund_for": "Gestione: {0}",
        "update_total_value": "Aggiorna il valore totale del fondo:",
        "current_total_value": "Valore Totale Attuale",
        "update_value": "Aggiorna Valore",
        "perform_operation": "Esegui un'operazione:",
        "operation_amount": "Importo Operazione",
        "linked_account": "Conto per Versamento/Prelievo",
        "deposit_from_account": "Versa da Conto",
        "deposit_from_external": "Versa da Esterno",
        "deposit_from_external_tooltip": "Es. da datore di lavoro",
        "withdraw_to_account": "Preleva su Conto",
        "pension_fund_value_updated": "Valore del fondo pensione aggiornato!",
        "error_updating_value": "Errore durante l'aggiornamento.",
        "pension_fund_op_success": "Operazione sul fondo pensione registrata!",
        "pension_fund_op_error": "Errore durante la registrazione dell'operazione.",

        # Dialogo Immobili
        "manage_property_dialog": "Gestione Immobile",
        "add_property": "Aggiungi Immobile",
        "edit_property": "Modifica Immobile",
        "property_name": "Nome Immobile",
        "address": "Via",
        "city": "Città",
        "bare_ownership": "Nuda Proprietà",
        "linked_mortgage": "Mutuo Collegato",
        "create_new_mortgage": "Nuovo Mutuo",

        # Dialogo Portafoglio
        "manage_portfolio_dialog": "Gestione Portafoglio",
        "total_portfolio_value": "Valore Totale Portafoglio",
        "total_gain_loss": "Gain/Loss Totale",
        "add_operation": "Aggiungi Operazione",
        "unit_price": "Prezzo Unitario",
        "buy": "Compra",
        "sell": "Vendi",
        "update_price": "Aggiorna Prezzo",
        "new_price": "Nuovo Prezzo",
        "edit_asset_details": "Modifica Dettagli Asset",

        # Dialogo Prestiti
        "manage_loan_dialog": "Gestione Prestito",
        "edit_loan": "Modifica Prestito",
        "loan_name": "Nome Prestito",
        "loan_type": "Tipo",
        "interest_amount": "Importo Interessi",
        "installment_due_day": "Giorno Scadenza Rata",
        "default_payment_account": "Conto Pagamento Predefinito",
        "default_payment_category": "Categoria Pagamento Predefinita",
        "pay_installment_dialog_title": "Paga Rata",
        "payment_amount": "Importo Pagamento",
        "payment_date": "Data Pagamento",
        "payment_account": "Conto di Pagamento",
        "payment_category": "Categoria di Pagamento",
        "execute_payment": "Esegui Pagamento",
        "total_installments": "Totale Rate",
        "paid_installments": "Rate Pagate",
        "remaining_installments": "Rate Rimanenti",

        # Scheda Conti Personali
        "net_worth": "Patrimonio Netto",
        "liquidity": "Liquidità",
        "investments": "Investimenti",
        "my_personal_accounts": "I Miei Conti Personali",
        "add_personal_account": "Aggiungi nuovo conto personale",
        "no_personal_accounts": "Non hai ancora aggiunto nessun conto personale.",
        "current_balance": "Saldo Attuale",
        "value": "Valore",
        "manage_portfolio": "Gestisci Portafoglio",
        "manage_pension_fund": "Gestisci Fondo Pensione",

        # Scheda Conti Condivisi
        "no_shared_accounts": "Non partecipi ancora a nessun conto condiviso.",
        "shared_type_family": "Tutta la Famiglia",
        "shared_type_users": "Utenti Specifici",

        # Scheda Personale (I Miei Dati)
        "welcome_back": "Bentornato, {0}!",
        "total_wealth": "Patrimonio Totale",
        "liquidity_details": "(di cui {0} in liquidità al {1})",
        "latest_transactions": "Ultime Transazioni (Liquidità)",
        "filter_by_month": "Filtra per Mese",

        # Scheda Famiglia
        "wealth_by_member": "Patrimonio per Membro",
        "total_family_wealth": "Patrimonio Totale Famiglia",
        "total_liquidity": "Liquidità Totale",
        "total_investments": "Investimenti Totali",
        "all_family_transactions": "Tutte le Transazioni della Famiglia",
        "user": "Utente",
        "date": "Data",
        "description": "Descrizione",
        "account": "Conto",
        "amount": "Importo",
        "no_transactions_found_family": "Nessuna transazione trovata per la famiglia.",
        "shared": "Condiviso",
        "no_family_access_permission": "Non hai i permessi per visualizzare questa sezione.",
        "not_in_family": "Non sei ancora stato aggiunto a una famiglia.",

        # Scheda Budget
        "budget_management": "Gestione Budget",
        "budget_description": "Imposta e monitora i limiti di spesa mensili per categoria.",
        "set_budget": "Imposta Budget",
        "no_budget_set": "Nessun budget impostato. Clicca su '+' per iniziare.",
        "spent": "Spesi",
        "of": "di",
        "remaining": "Rimanenti",
        "set_monthly_budget": "Imposta Budget Mensile",
        "limit_amount": "Importo Limite",
        "budget_saved": "Budget salvato con successo!",
        "budget_amount": "Totale Budget",
        "subcategory": "Sottocategoria",
        "category": "Categoria",

        # Scheda Spese Fisse
        "fixed_expenses_management": "Gestione Spese Fisse",
        "fixed_expenses_description": "Configura qui le tue spese ricorrenti (es. affitto, abbonamenti). Verranno addebitate automaticamente ogni mese.",
        "name": "Nome",
        "surname": "Cognome",
        "password_updated_success": "Password aggiornata con successo! Ora puoi effettuare il login.",
        "invalid_or_expired_token": "Token non valido o scaduto. Richiedi un nuovo reset.",
        "reset_link_sent_confirmation": "Se esiste un account associato a questa email, è stata inviata una password temporanea.",
        "no_account_question": "Non hai un account?",
        "register_now": "Registrati",

        # Pannello Admin
        "categories_management": "Gestione Categorie",
        "subcategory": "Sottocategoria",
        "members_management": "Gestione Membri",
        "admin_google_settings": "Google",
        "add_category": "Aggiungi Categoria",
        "add_subcategory": "Aggiungi Sottocategoria",
        "category_name": "Nome Categoria",
        "subcategory_name": "Nome Sottocategoria",
        "no_categories_found": "Nessuna categoria trovata.",
        "invite_member": "Invita Membro",
        "username_or_email": "Username o Email",
        "role": "Ruolo",
        "edit_role_for": "Modifica ruolo per",
        "username": "Username",
        "email": "Email",
        "invite": "Invita",
        "remove_from_family": "Rimuovi dalla famiglia",
        "no_members_found": "Nessun altro membro nella famiglia.",

        # Dialogo Transazioni
        "expense": "Spesa",
        "income": "Incasso",
        "category_optional": "Categoria (opzionale)",
        "shared_suffix": "(Condiviso)",
        "personal_suffix": "(Personale)",

        # Dialogo Conti
        "manage_account": "Gestisci Conto",
        "add_account": "Aggiungi Conto",
        "edit_account": "Modifica Conto",
        "account_name_placeholder": "Nome Conto (es. Conto Principale)",
        "account_type": "Tipo di Conto",
        "iban_optional": "IBAN (Opzionale)",
        "initial_balance_optional": "Saldo Iniziale (Opzionale)",
        "set_initial_balance": "Imposta Saldo Iniziale",
        "add_initial_asset": "Aggiungi Asset Iniziale",
        "initial_assets": "Asset Iniziali:",
        "initial_assets_desc": "Inserisci il valore attuale e il G/L totale pre-esistente (opzionale).",
        "ticker": "Ticker",
        "asset_name": "Nome Asset",
        "quantity": "Quantità",
        "current_unit_price": "Px Attuale Unit.",
        "past_gain_loss": "G/L Tot. Pregresso",
        "remove_asset": "Rimuovi Asset",
        "set_as_default_account": "Imposta come conto predefinito per le spese",
        "iban_in_use_or_invalid": "IBAN già in uso o non valido",

        # Dialogo Conti Condivisi
        "manage_shared_account_dialog": "Gestisci Conto Condiviso",
        "create_shared_account": "Crea Conto Condiviso",
        "edit_shared_account": "Modifica Conto Condiviso",
        "shared_account_name": "Nome Conto Condiviso",
        "sharing_type": "Tipo di Condivisione",
        "sharing_type_family": "Tutta la Famiglia (gestito da Admin)",
        "sharing_type_users": "Utenti Specifici",
        "select_participants": "Seleziona Partecipanti (solo per 'Utenti Specifici'):",
        "select_at_least_one_participant": "Seleziona almeno un partecipante per i conti 'Utenti Specifici'.",

        # Dialogo Giroconto
        "new_transfer_dialog": "Nuovo Giroconto",
        "from_account": "Da Conto (Sorgente)",
        "to_account": "A Conto (Destinazione)",
        "transfer_description_placeholder": "Descrizione (es. Spese comuni)",
        "accounts_must_be_different": "I conti devono essere diversi",
        "select_source_account": "Seleziona un conto di origine",
        "select_destination_account": "Seleziona un conto di destinazione",
        "execute_transfer": "Esegui Giroconto",

        # Dialogo Spese Fisse
        "manage_fixed_expense": "Gestisci Spesa Fissa",
        "add_fixed_expense": "Aggiungi Spesa Fissa",
        "edit_fixed_expense": "Modifica Spesa Fissa",
        "expense_name_placeholder": "Nome Spesa (es. Abbonamento Netflix)",
        "debit_account": "Conto di Addebito",
        "debit_day": "Giorno del Mese per l'Addebito",

        # Dialogo Fondo Pensione
        "manage_pension_fund_dialog": "Gestione Fondo Pensione",
        "manage_pension_fund_for": "Gestione: {0}",
        "update_total_value": "Aggiorna il valore totale del fondo:",
        "current_total_value": "Valore Totale Attuale",
        "update_value": "Aggiorna Valore",
        "perform_operation": "Esegui un'operazione:",
        "operation_amount": "Importo Operazione",
        "linked_account": "Conto per Versamento/Prelievo",
        "deposit_from_account": "Versa da Conto",
        "deposit_from_external": "Versa da Esterno",
        "deposit_from_external_tooltip": "Es. da datore di lavoro",
        "withdraw_to_account": "Preleva su Conto",
        "pension_fund_value_updated": "Valore del fondo pensione aggiornato!",
        "error_updating_value": "Errore durante l'aggiornamento.",
        "pension_fund_op_success": "Operazione sul fondo pensione registrata!",
        "pension_fund_op_error": "Errore durante la registrazione dell'operazione.",

        # Dialogo Immobili
        "manage_property_dialog": "Gestione Immobile",
        "add_property": "Aggiungi Immobile",
        "edit_property": "Modifica Immobile",
        "property_name": "Nome Immobile",
        "address": "Via",
        "city": "Città",
        "bare_ownership": "Nuda Proprietà",
        "linked_mortgage": "Mutuo Collegato",
        "create_new_mortgage": "Nuovo Mutuo",

        # Dialogo Portafoglio
        "manage_portfolio_dialog": "Gestione Portafoglio",
        "total_portfolio_value": "Valore Totale Portafoglio",
        "total_gain_loss": "Gain/Loss Totale",
        "add_operation": "Aggiungi Operazione",
        "unit_price": "Prezzo Unitario",
        "buy": "Compra",
        "sell": "Vendi",
        "update_price": "Aggiorna Prezzo",
        "new_price": "Nuovo Prezzo",
        "edit_asset_details": "Modifica Dettagli Asset",

        # Dialogo Prestiti
        "manage_loan_dialog": "Gestione Prestito",
        "edit_loan": "Modifica Prestito",
        "loan_name": "Nome Prestito",
        "loan_type": "Tipo",
        "interest_amount": "Importo Interessi",
        "installment_due_day": "Giorno Scadenza Rata",
        "default_payment_account": "Conto Pagamento Predefinito",
        "default_payment_category": "Categoria Pagamento Predefinita",
        "pay_installment_dialog_title": "Paga Rata",
        "payment_amount": "Importo Pagamento",
        "payment_date": "Data Pagamento",
        "payment_account": "Conto di Pagamento",
        "payment_category": "Categoria di Pagamento",
        "execute_payment": "Esegui Pagamento",
        "total_installments": "Totale Rate",
        "paid_installments": "Rate Pagate",
        "remaining_installments": "Rate Rimanenti",

        # Scheda Conti Personali
        "net_worth": "Patrimonio Netto",
        "liquidity": "Liquidità",
        "investments": "Investimenti",
        "my_personal_accounts": "I Miei Conti Personali",
        "add_personal_account": "Aggiungi nuovo conto personale",
        "no_personal_accounts": "Non hai ancora aggiunto nessun conto personale.",
        "current_balance": "Saldo Attuale",
        "value": "Valore",
        "manage_portfolio": "Gestisci Portafoglio",
        "manage_pension_fund": "Gestisci Fondo Pensione",

        # Scheda Conti Condivisi
        "no_shared_accounts": "Non partecipi ancora a nessun conto condiviso.",
        "shared_type_family": "Tutta la Famiglia",
        "shared_type_users": "Utenti Specifici",

        # Scheda Personale (I Miei Dati)
        "welcome_back": "Bentornato, {0}!",
        "total_wealth": "Patrimonio Totale",
        "liquidity_details": "(di cui {0} in liquidità al {1})",
        "latest_transactions": "Ultime Transazioni (Liquidità)",
        "filter_by_month": "Filtra per Mese",

        # Scheda Famiglia
        "wealth_by_member": "Patrimonio per Membro",
        "total_family_wealth": "Patrimonio Totale Famiglia",
        "total_liquidity": "Liquidità Totale",
        "total_investments": "Investimenti Totali",
        "all_family_transactions": "Tutte le Transazioni della Famiglia",
        "user": "Utente",
        "date": "Data",
        "description": "Descrizione",
        "account": "Conto",
        "amount": "Importo",
        "no_transactions_found_family": "Nessuna transazione trovata per la famiglia.",
        "shared": "Condiviso",
        "no_family_access_permission": "Non hai i permessi per visualizzare questa sezione.",
        "not_in_family": "Non sei ancora stato aggiunto a una famiglia.",

        # Scheda Budget
        "budget_management": "Gestione Budget",
        "budget_description": "Imposta e monitora i limiti di spesa mensili per categoria.",
        "set_budget": "Imposta Budget",
        "no_budget_set": "Nessun budget impostato. Clicca su '+' per iniziare.",
        "spent": "Spesi",
        "of": "di",
        "remaining": "Rimanenti",
        "set_monthly_budget": "Imposta Budget Mensile",
        "limit_amount": "Importo Limite",
        "budget_saved": "Budget salvato con successo!",
        "budget_amount": "Totale Budget",

        # Scheda Spese Fisse
        "fixed_expenses_management": "Gestione Spese Fisse",
        "fixed_expenses_description": "Configura qui le tue spese ricorrenti (es. affitto, abbonamenti). Verranno addebitate automaticamente ogni mese.",
        "name": "Nome",
        "surname": "Cognome",
        "active": "Attiva",
        "actions": "Azioni",
        "no_fixed_expenses": "Nessuna spesa fissa configurata.",

        # Scheda Prestiti
        "loans_management": "Gestione Prestiti",
        "loans_description": "Tieni traccia di mutui, finanziamenti e prestiti.",
        "add_loan": "Aggiungi Prestito",
        "pay_installment": "Paga Rata",
        "financed_amount": "Importo Finanziato",
        "remaining_amount": "Importo Residuo",
        "monthly_installment": "Rata Mensile",
        "total_months": "Mesi Totali",
        "no_loans": "Nessun prestito inserito.",

        # Scheda Immobili
        "properties_management": "Gestione Immobili",
        "properties_description": "Gestisci il valore e i mutui associati ai tuoi immobili.",
        "purchase_value": "Valore d'Acquisto",
        "current_value": "Valore Attuale",
        "residual_mortgage": "Mutuo Residuo",
        "no_properties": "Nessun immobile inserito.",

        # Scheda Impostazioni - Profilo Utente
        "user_profile": "Profilo Utente",
        "user_profile_desc": "Modifica le tue informazioni personali e la password.",
        "date_of_birth": "Data di Nascita",
        "tax_code": "Codice Fiscale",
        "address": "Indirizzo",
        "change_password": "Cambia Password",
        "save_profile": "Salva Profilo",
        "profile_saved_success": "Profilo salvato con successo!",

        # Scheda Impostazioni
        "google_settings": "Impostazioni Google",
        "google_settings_desc": "Connetti il tuo account Google per sincronizzare il database su Google Drive.",
        "status_connected": "Stato: Connesso",
        "status_disconnected": "Stato: Non connesso",
        "connect_google_account": "Connetti Account Google",
        "disconnect_google_account": "Disconnetti Account Google",
        "sync_db_drive": "Sincronizza Database su Drive",
        "sync_db_drive_tooltip": "Carica il DB locale su Google Drive (sovrascrive)",
        "language_and_currency": "Lingua e Valuta",
        "language_and_currency_desc": "Scegli la lingua e la valuta per l'applicazione.",
        "language": "Lingua",
        "currency": "Valuta",
        "default_account": "Conto Predefinito",
        "default_account_desc": "Seleziona un conto da usare come predefinito per le nuove transazioni.",
        "save_default_account": "Salva Conto Predefinito",
        "backup_and_restore": "Backup e Ripristino",
        "backup_and_restore_desc": "Salva una copia di sicurezza dei tuoi dati o ripristina da un backup precedente.",
        "create_backup": "Crea Backup Dati",
        "restore_from_backup": "Ripristina da Backup",

        #nuovi campi inseriti da sistemare IT
        "manage_shared_account": "Gestisci Conto Condiviso",
        "debit_day_of_month": "Giorno del Mese",
        "select_existing_asset_optional": "Seleziona Asset Esistente (opzionale)",
        "invalid_amount_or_quantity": "Importo o quantità non validi",
        "create_new_mortgage": "Crea Nuovo Mutuo",
        "default_payment_subcategory": "Sottocategoria Pagamento Predefinita",
        "start_date": "Data Inizio",
        "required_field": "Campo obbligatorio",
        "delete_account": "Elimina Conto",
        "auto_debit": "Addebito Automatico",
        "auto_debit_desc": "Seleziona se l'addebito deve essere eseguito automaticamente ogni mese.",
        "manage_shared_account": "Gestisci Conto Condiviso",
        "debit_day_of_month": "Giorno del Mese",
        "select_existing_asset_optional": "Seleziona Asset Esistente (opzionale)",
        "invalid_amount_or_quantity": "Importo o quantità non validi",
        "create_new_mortgage": "Crea Nuovo Mutuo",
        "default_payment_subcategory": "Sottocategoria Pagamento Predefinita",
        "start_date": "Data Inizio",
        "required_field": "Campo obbligatorio",
        "delete_account": "Elimina Conto",

    },
    "en": {
        # Generali
        "app_title": "Family Budget",
        "edit": "Edit",
        "delete": "Delete",
        "save": "Save",
        "cancel": "Cancel",
        "close": "Close",
        "add": "Add",
        "new_transaction": "New Transaction",
        "new_transfer": "New Transfer",
        "no_category": "No Category",
        "confirm_delete_title": "Confirm Deletion",
        "confirm_delete_content": "Are you sure you want to delete this item? This action is irreversible.",
        "yes_delete": "Yes, Delete",
        "fill_all_fields": "Please fill all required fields.",
        "invalid_amount": "Invalid amount.",
        "amount_not_zero": "Amount cannot be zero.",
        "description_required": "Description is required.",
        "error_dialog_title": "Error",
        "select_an_account": "Select an account.",

        # Schede Principali
        "my_data": "My Data",
        "budget": "Budget",
        "personal_accounts": "Personal Accounts",
        "shared_accounts": "Shared Accounts",
        "fixed_expenses": "Fixed Expenses",
        "loans": "Loans",
        "properties": "Properties",
        "family": "Family",

        # Azioni AppBar
        "settings": "Settings",
        "admin_panel_title": "Admin Panel",
        "export_data": "Export Data",
        "logout": "Logout",
        "info": "Information",

        # Recupero Password
        "forgot_password": "Forgot password?",
        "password_recovery_title": "Password Recovery",
        "password_recovery_desc": "Enter your email to receive a temporary password.",
        "send_reset_link": "Send Temporary Password",
        "back_to_login": "Back to Login",
        "email_is_required": "Email is required.",
        "set_new_password_title": "Create a New Password",
        "new_password": "New Password",
        "confirm_new_password": "Confirm New Password",
        "save_new_password": "Save New Password",
        "passwords_do_not_match": "Passwords do not match or are empty.",
        "password_updated_success": "Password updated successfully! You can now log in.",
        "invalid_or_expired_token": "Invalid or expired token. Please request a new reset.",
        "reset_link_sent_confirmation": "If an account is associated with this email, a temporary password has been sent.",
        "no_account_question": "Don't have an account?",
        "register_now": "Register now",

        # Pannello Admin
        "categories_management": "Categories Management",
        "members_management": "Members Management",
        "admin_google_settings": "Google",
        "add_category": "Add Category",
        "category_name": "Category Name",
        "subcategory_name": "Subcategory Name",
        "no_categories_found": "No categories found.",
        "invite_member": "Invite Member",
        "username_or_email": "Username or Email",
        "role": "Role",
        "username": "Username",
        "email": "Email",
        "invite": "Invite",
        "remove_from_family": "Remove from family",
        "no_members_found": "No other members in the family.",

        # Dialogo Transazioni
        "expense": "Expense",
        "income": "Income",
        "category_optional": "Category (optional)",
        "shared_suffix": "(Shared)",
        "personal_suffix": "(Personal)",

        # Dialogo Conti
        "manage_account": "Manage Account",
        "add_account": "Add Account",
        "edit_account": "Edit Account",
        "account_name_placeholder": "Account Name (e.g., Main Account)",
        "account_type": "Account Type",
        "iban_optional": "IBAN (Optional)",
        "initial_balance_optional": "Initial Balance (Optional)",
        "set_initial_balance": "Set Initial Balance",
        "add_initial_asset": "Add Initial Asset",
        "initial_assets": "Initial Assets:",
        "initial_assets_desc": "Enter the current value and the total pre-existing G/L (optional).",
        "ticker": "Ticker",
        "asset_name": "Asset Name",
        "quantity": "Quantity",
        "current_unit_price": "Current Unit Px.",
        "past_gain_loss": "Past Total G/L",
        "remove_asset": "Remove Asset",
        "set_as_default_account": "Set as default account for expenses",
        "iban_in_use_or_invalid": "IBAN already in use or invalid",

        # Dialogo Conti Condivisi
        "manage_shared_account_dialog": "Manage Shared Account",
        "create_shared_account": "Create Shared Account",
        "edit_shared_account": "Edit Shared Account",
        "shared_account_name": "Shared Account Name",
        "sharing_type": "Sharing Type",
        "sharing_type_family": "Whole Family (managed by Admin)",
        "sharing_type_users": "Specific Users",
        "select_participants": "Select Participants (for 'Specific Users' only):",
        "select_at_least_one_participant": "Select at least one participant for 'Specific Users' accounts.",

        # Dialogo Giroconto
        "new_transfer_dialog": "New Transfer",
        "from_account": "From Account (Source)",
        "to_account": "To Account (Destination)",
        "transfer_description_placeholder": "Description (e.g., Common expenses)",
        "accounts_must_be_different": "Accounts must be different",
        "select_source_account": "Select a source account",
        "select_destination_account": "Select a destination account",
        "execute_transfer": "Execute Transfer",

        # Dialogo Spese Fisse
        "manage_fixed_expense": "Manage Fixed Expense",
        "add_fixed_expense": "Add Fixed Expense",
        "edit_fixed_expense": "Edit Fixed Expense",
        "expense_name_placeholder": "Expense Name (e.g., Netflix Subscription)",
        "debit_account": "Debit Account",
        "debit_day": "Day of the Month for Debit",

        # Dialogo Fondo Pensione
        "manage_pension_fund_dialog": "Pension Fund Management",
        "manage_pension_fund_for": "Management: {0}",
        "update_total_value": "Update the total value of the fund:",
        "current_total_value": "Current Total Value",
        "update_value": "Update Value",
        "perform_operation": "Perform an operation:",
        "operation_amount": "Operation Amount",
        "linked_account": "Account for Deposit/Withdrawal",
        "deposit_from_account": "Deposit from Account",
        "deposit_from_external": "Deposit from External",
        "deposit_from_external_tooltip": "E.g., from employer",
        "withdraw_to_account": "Withdraw to Account",
        "pension_fund_value_updated": "Pension fund value updated!",
        "error_updating_value": "Error during update.",
        "pension_fund_op_success": "Pension fund operation recorded!",
        "pension_fund_op_error": "Error recording the operation.",

        # Dialogo Immobili
        "manage_property_dialog": "Property Management",
        "add_property": "Add Property",
        "edit_property": "Edit Property",
        "property_name": "Property Name",
        "address": "Address",
        "city": "City",
        "bare_ownership": "Bare Ownership",
        "linked_mortgage": "Linked Mortgage",

        # Dialogo Portafoglio
        "manage_portfolio_dialog": "Portfolio Management",
        "total_portfolio_value": "Total Portfolio Value",
        "total_gain_loss": "Total Gain/Loss",
        "add_operation": "Add Operation",
        "unit_price": "Unit Price",
        "buy": "Buy",
        "sell": "Sell",
        "update_price": "Update Price",
        "new_price": "New Price",
        "edit_asset_details": "Edit Asset Details",

        # Dialogo Prestiti
        "manage_loan_dialog": "Loan Management",
        "edit_loan": "Edit Loan",
        "loan_name": "Loan Name",
        "loan_type": "Type",
        "interest_amount": "Interest Amount",
        "installment_due_day": "Installment Due Day",
        "default_payment_account": "Default Payment Account",
        "default_payment_category": "Default Payment Category",
        "pay_installment_dialog_title": "Pay Installment",
        "payment_amount": "Payment Amount",
        "payment_date": "Payment Date",
        "payment_account": "Payment Account",
        "payment_category": "Payment Category",
        "execute_payment": "Execute Payment",

        # Scheda Conti Personali
        "net_worth": "Net Worth",
        "liquidity": "Liquidity",
        "investments": "Investments",
        "my_personal_accounts": "My Personal Accounts",
        "add_personal_account": "Add new personal account",
        "no_personal_accounts": "You haven't added any personal accounts yet.",
        "current_balance": "Current Balance",
        "value": "Value",
        "manage_portfolio": "Manage Portfolio",
        "manage_pension_fund": "Manage Pension Fund",

        # Scheda Conti Condivisi
        "no_shared_accounts": "You are not part of any shared accounts yet.",
        "shared_type_family": "Whole Family",
        "shared_type_users": "Specific Users",

        # Scheda Personale (I Miei Dati)
        "welcome_back": "Welcome back, {0}!",
        "total_wealth": "Total Wealth",
        "liquidity_details": "({0} in liquidity as of {1})",
        "latest_transactions": "Latest Transactions (Liquidity)",
        "filter_by_month": "Filter by Month",

        # Scheda Famiglia
        "wealth_by_member": "Wealth by Member",
        "total_family_wealth": "Total Family Wealth",
        "total_liquidity": "Total Liquidity",
        "total_investments": "Total Investments",
        "all_family_transactions": "All Family Transactions",
        "user": "User",
        "date": "Date",
        "description": "Description",
        "account": "Account",
        "amount": "Amount",
        "no_transactions_found_family": "No transactions found for the family.",
        "shared": "Shared",
        "no_family_access_permission": "You do not have permission to view this section.",
        "not_in_family": "You have not been added to a family yet.",

        # Scheda Budget
        "budget_management": "Budget Management",
        "budget_description": "Set and monitor monthly spending limits by category.",
        "set_budget": "Set Budget",
        "no_budget_set": "No budget set. Click '+' to start.",
        "spent": "Spent",
        "of": "of",
        "remaining": "Remaining",
        "set_monthly_budget": "Set Monthly Budget",
        "limit_amount": "Limit Amount",
        "budget_saved": "Budget saved successfully!",

        # Scheda Spese Fisse
        "fixed_expenses_management": "Fixed Expenses Management",
        "fixed_expenses_description": "Set up your recurring expenses here (e.g., rent, subscriptions). They will be charged automatically each month.",
        "name": "Name",
        "active": "Active",
        "actions": "Actions",
        "no_fixed_expenses": "No fixed expenses configured.",

        # Scheda Prestiti
        "loans_management": "Loan Management",
        "loans_description": "Track mortgages, financing, and loans.",
        "add_loan": "Add Loan",
        "pay_installment": "Pay Installment",
        "financed_amount": "Financed Amount",
        "remaining_amount": "Remaining Amount",
        "monthly_installment": "Monthly Installment",
        "total_months": "Total Months",
        "no_loans": "No loans entered.",

        # Scheda Immobili
        "properties_management": "Property Management",
        "properties_description": "Manage the value and associated mortgages of your properties.",
        "add_property": "Add Property",
        "purchase_value": "Purchase Value",
        "current_value": "Current Value",
        "residual_mortgage": "Residual Mortgage",
        "no_properties": "No properties entered.",

        # Scheda Impostazioni - Profilo Utente
        "user_profile": "User Profile",
        "user_profile_desc": "Edit your personal information and password.",
        "date_of_birth": "Date of Birth",
        "tax_code": "Tax Code",
        "address": "Address",
        "change_password": "Change Password",
        "save_profile": "Save Profile",
        "profile_saved_success": "Profile saved successfully!",

        # Scheda Impostazioni
        "google_settings": "Google Settings",
        "google_settings_desc": "Connect your Google account to sync the database to Google Drive.",
        "status_connected": "Status: Connected",
        "status_disconnected": "Status: Not Connected",
        "connect_google_account": "Connect Google Account",
        "disconnect_google_account": "Disconnect Google Account",
        "sync_db_drive": "Sync Database to Drive",
        "sync_db_drive_tooltip": "Upload local DB to Google Drive (overwrites)",
        "language_and_currency": "Language and Currency",
        "language_and_currency_desc": "Choose the language and currency for the application.",
        "language": "Language",
        "currency": "Currency",
        "default_account": "Default Account",
        "default_account_desc": "Select a default account to use for new transactions.",
        "save_default_account": "Save Default Account",
        "backup_and_restore": "Backup and Restore",
        "backup_and_restore_desc": "Save a backup of your data or restore from a previous backup.",
        "create_backup": "Create Data Backup",
        "restore_from_backup": "Restore from Backup",

        #nuovi dati inseriti e da riorganizzare en
        "subcategory": "Subcategory",
        "category": "Category",
        "edit_role_for": "Edit role for",
        "avg_purchase_price": "Average Purchase Price",
        "avg_purchase_price_tooltip": "Weighted average purchase price of assets",
        "past_gain_loss_tooltip": "Total past Gain/Loss (before entering the system)",
        "manage_shared_account": "Manage Shared Account",
        "debit_day_of_month": "Day of the Month",
        "select_existing_asset_optional": "Select Existing Asset (optional)",
        "invalid_amount_or_quantity": "Invalid amount or quantity",
        "create_new_mortgage": "Create New Mortgage",
        "default_payment_subcategory": "Default Payment Subcategory",
        "start_date": "Start Date",
        "required_field": "Required field",
        "delete_account": "Delete Account",
        "auto_debit": "Auto Debit",
        "auto_debit_desc": "Select if the debit should be executed automatically every month.",

    },
    "es": {
        # Generali
        "app_title": "Presupuesto Familiar",
        "edit": "Editar",
        "delete": "Eliminar",
        "save": "Guardar",
        "cancel": "Cancelar",
        "close": "Cerrar",
        "add": "Añadir",
        "new_transaction": "Nueva Transacción",
        "new_transfer": "Nueva Transferencia",
        "no_category": "Sin Categoría",
        "confirm_delete_title": "Confirmar Eliminación",
        "confirm_delete_content": "¿Estás seguro de que quieres eliminar este elemento? La acción es irreversible.",
        "yes_delete": "Sí, Eliminar",
        "fill_all_fields": "Por favor, rellena todos los campos obligatorios.",
        "invalid_amount": "Importe no válido.",
        "amount_not_zero": "El importe no puede ser cero.",
        "description_required": "La descripción es obligatoria.",
        "error_dialog_title": "Error",
        "select_an_account": "Selecciona una cuenta.",

        # Schede Principali
        "my_data": "Mis Datos",
        "budget": "Presupuesto",
        "personal_accounts": "Cuentas Personales",
        "shared_accounts": "Cuentas Compartidas",
        "fixed_expenses": "Gastos Fijos",
        "loans": "Préstamos",
        "properties": "Inmuebles",
        "family": "Familia",

        # Azioni AppBar
        "settings": "Configuración",
        "admin_panel_title": "Panel de Admin",
        "export_data": "Exportar Datos",
        "logout": "Cerrar Sesión",
        "info": "Información",

        # Recupero Password
        "forgot_password": "¿Olvidaste tu contraseña?",
        "password_recovery_title": "Recuperar Contraseña",
        "password_recovery_desc": "Introduce tu email para recibir una contraseña temporal.",
        "send_reset_link": "Enviar Contraseña Temporal",
        "back_to_login": "Volver al Inicio de Sesión",
        "email_is_required": "El email es obligatorio.",
        "set_new_password_title": "Crear una Nueva Contraseña",
        "new_password": "Nueva Contraseña",
        "confirm_new_password": "Confirmar Nueva Contraseña",
        "save_new_password": "Guardar Nueva Contraseña",
        "passwords_do_not_match": "Las contraseñas no coinciden o están vacías.",
        "password_updated_success": "¡Contraseña actualizada con éxito! Ahora puedes iniciar sesión.",
        "invalid_or_expired_token": "Token no válido o caducado. Por favor, solicita un nuevo restablecimiento.",
        "reset_link_sent_confirmation": "Si existe una cuenta asociada a este email, se ha enviado una contraseña temporal.",
        "no_account_question": "¿No tienes una cuenta?",
        "register_now": "Regístrate ahora",

        # Pannello Admin
        "categories_management": "Gestión de Categorías",
        "members_management": "Gestión de Miembros",
        "admin_google_settings": "Google",
        "add_category": "Añadir Categoría",
        "category_name": "Nombre de la Categoría",
        "no_categories_found": "No se encontraron categorías.",
        "invite_member": "Invitar Miembro",
        "username_or_email": "Usuario o Email",
        "role": "Rol",
        "username": "Usuario",
        "email": "Email",
        "invite": "Invitar",
        "remove_from_family": "Eliminar de la familia",
        "no_members_found": "No hay otros miembros en la familia.",

        # Dialogo Transazioni
        "expense": "Gasto",
        "income": "Ingreso",
        "category_optional": "Categoría (opcional)",
        "shared_suffix": "(Compartida)",
        "personal_suffix": "(Personal)",

        # Dialogo Conti
        "manage_account": "Gestionar Cuenta",
        "add_account": "Añadir Cuenta",
        "edit_account": "Editar Cuenta",
        "account_name_placeholder": "Nombre de la Cuenta (ej. Cuenta Principal)",
        "account_type": "Tipo de Cuenta",
        "iban_optional": "IBAN (Opcional)",
        "initial_balance_optional": "Saldo Inicial (Opcional)",
        "set_initial_balance": "Establecer Saldo Inicial",
        "add_initial_asset": "Añadir Activo Inicial",
        "initial_assets": "Activos Iniciales:",
        "initial_assets_desc": "Introduce el valor actual y la G/P total preexistente (opcional).",
        "ticker": "Ticker",
        "asset_name": "Nombre del Activo",
        "quantity": "Cantidad",
        "current_unit_price": "Px Actual Unit.",
        "past_gain_loss": "G/P Tot. Anterior",
        "remove_asset": "Eliminar Activo",
        "set_as_default_account": "Establecer como cuenta predeterminada para gastos",
        "iban_in_use_or_invalid": "IBAN ya en uso o no válido",

        # Dialogo Conti Condivisi
        "manage_shared_account_dialog": "Gestionar Cuenta Compartida",
        "create_shared_account": "Crear Cuenta Compartida",
        "edit_shared_account": "Editar Cuenta Compartida",
        "shared_account_name": "Nombre de la Cuenta Compartida",
        "sharing_type": "Tipo de Compartición",
        "sharing_type_family": "Toda la Familia (gestionado por Admin)",
        "sharing_type_users": "Usuarios Específicos",
        "select_participants": "Seleccionar Participantes (solo para 'Usuarios Específicos'):",
        "select_at_least_one_participant": "Selecciona al menos un participante para las cuentas de 'Usuarios Específicos'.",

        # Dialogo Giroconto
        "new_transfer_dialog": "Nueva Transferencia",
        "from_account": "De la Cuenta (Origen)",
        "to_account": "A la Cuenta (Destino)",
        "transfer_description_placeholder": "Descripción (ej. Gastos comunes)",
        "accounts_must_be_different": "Las cuentas deben ser diferentes",
        "select_source_account": "Selecciona una cuenta de origen",
        "select_destination_account": "Selecciona una cuenta de destino",
        "execute_transfer": "Ejecutar Transferencia",

        # Dialogo Spese Fisse
        "manage_fixed_expense": "Gestionar Gasto Fijo",
        "add_fixed_expense": "Añadir Gasto Fijo",
        "edit_fixed_expense": "Editar Gasto Fijo",
        "expense_name_placeholder": "Nombre del Gasto (ej. Suscripción a Netflix)",
        "debit_account": "Cuenta de Débito",
        "debit_day": "Día del Mes para el Débito",

        # Dialogo Fondo Pensione
        "manage_pension_fund_dialog": "Gestión de Fondo de Pensiones",
        "manage_pension_fund_for": "Gestión: {0}",
        "update_total_value": "Actualizar el valor total del fondo:",
        "current_total_value": "Valor Total Actual",
        "update_value": "Actualizar Valor",
        "perform_operation": "Realizar una operación:",
        "operation_amount": "Importe de la Operación",
        "linked_account": "Cuenta para Depósito/Retiro",
        "deposit_from_account": "Depositar desde Cuenta",
        "deposit_from_external": "Depositar desde Externo",
        "deposit_from_external_tooltip": "Ej. del empleador",
        "withdraw_to_account": "Retirar a Cuenta",
        "pension_fund_value_updated": "¡Valor del fondo de pensiones actualizado!",
        "error_updating_value": "Error al actualizar.",
        "pension_fund_op_success": "¡Operación en el fondo de pensiones registrada!",
        "pension_fund_op_error": "Error al registrar la operación.",

        # Dialogo Immobili
        "manage_property_dialog": "Gestión de Inmuebles",
        "add_property": "Añadir Inmueble",
        "edit_property": "Editar Inmueble",
        "property_name": "Nombre del Inmueble",
        "address": "Dirección",
        "city": "Ciudad",
        "bare_ownership": "Nuda Propiedad",
        "linked_mortgage": "Hipoteca Vinculada",

        # Dialogo Portafoglio
        "manage_portfolio_dialog": "Gestión de Cartera",
        "total_portfolio_value": "Valor Total de la Cartera",
        "total_gain_loss": "Ganancia/Pérdida Total",
        "add_operation": "Añadir Operación",
        "unit_price": "Precio Unitario",
        "buy": "Comprar",
        "sell": "Vender",
        "update_price": "Actualizar Precio",
        "new_price": "Nuevo Precio",
        "edit_asset_details": "Editar Detalles del Activo",

        # Dialogo Prestiti
        "manage_loan_dialog": "Gestión de Préstamos",
        "edit_loan": "Editar Préstamo",
        "loan_name": "Nombre del Préstamo",
        "loan_type": "Tipo",
        "interest_amount": "Importe de Intereses",
        "installment_due_day": "Día de Vencimiento de la Cuota",
        "default_payment_account": "Cuenta de Pago Predeterminada",
        "default_payment_category": "Categoría de Pago Predeterminada",
        "pay_installment_dialog_title": "Pagar Cuota",
        "payment_amount": "Importe del Pago",
        "payment_date": "Fecha de Pago",
        "payment_account": "Cuenta de Pago",
        "payment_category": "Categoría de Pago",
        "execute_payment": "Ejecutar Pago",

        # Scheda Conti Personali
        "net_worth": "Patrimonio Neto",
        "liquidity": "Liquidez",
        "investments": "Inversiones",
        "my_personal_accounts": "Mis Cuentas Personales",
        "add_personal_account": "Añadir nueva cuenta personal",
        "no_personal_accounts": "Aún no has añadido ninguna cuenta personal.",
        "current_balance": "Saldo Actual",
        "value": "Valor",
        "manage_portfolio": "Gestionar Cartera",
        "manage_pension_fund": "Gestionar Fondo de Pensiones",

        # Scheda Conti Condivisi
        "no_shared_accounts": "Aún no participas en ninguna cuenta compartida.",
        "shared_type_family": "Toda la Familia",
        "shared_type_users": "Usuarios Específicos",

        # Scheda Personale (I Miei Dati)
        "welcome_back": "¡Bienvenido de nuevo, {0}!",
        "total_wealth": "Patrimonio Total",
        "liquidity_details": "({0} en liquidez a fecha de {1})",
        "latest_transactions": "Últimas Transacciones (Liquidez)",
        "filter_by_month": "Filtrar por Mes",

        # Scheda Famiglia
        "wealth_by_member": "Patrimonio por Miembro",
        "total_family_wealth": "Patrimonio Total Familiar",
        "total_liquidity": "Liquidez Total",
        "total_investments": "Inversiones Totales",
        "all_family_transactions": "Todas las Transacciones Familiares",
        "user": "Usuario",
        "date": "Fecha",
        "description": "Descripción",
        "account": "Cuenta",
        "amount": "Importe",
        "no_transactions_found_family": "No se encontraron transacciones para la familia.",
        "shared": "Compartido",
        "no_family_access_permission": "No tienes permisos para ver esta sección.",
        "not_in_family": "Aún no has sido añadido a una familia.",

        # Scheda Budget
        "budget_management": "Gestión de Presupuesto",
        "budget_description": "Establece y supervisa los límites de gasto mensuales por categoría.",
        "set_budget": "Establecer Presupuesto",
        "no_budget_set": "No hay presupuesto establecido. Haz clic en '+' para empezar.",
        "spent": "Gastado",
        "of": "de",
        "remaining": "Restante",
        "set_monthly_budget": "Establecer Presupuesto Mensual",
        "limit_amount": "Importe Límite",
        "budget_saved": "¡Presupuesto guardado con éxito!",

        # Scheda Spese Fisse
        "fixed_expenses_management": "Gestión de Gastos Fijos",
        "fixed_expenses_description": "Configura aquí tus gastos recurrentes (ej. alquiler, suscripciones). Se cargarán automáticamente cada mes.",
        "name": "Nombre",
        "active": "Activo",
        "actions": "Acciones",
        "no_fixed_expenses": "No hay gastos fijos configurados.",

        # Scheda Prestiti
        "loans_management": "Gestión de Préstamos",
        "loans_description": "Realiza un seguimiento de hipotecas, financiaciones y préstamos.",
        "add_loan": "Añadir Préstamo",
        "pay_installment": "Pagar Cuota",
        "financed_amount": "Importe Financiado",
        "remaining_amount": "Importe Restante",
        "monthly_installment": "Cuota Mensual",
        "total_months": "Meses Totales",
        "no_loans": "No se han introducido préstamos.",

        # Scheda Immobili
        "properties_management": "Gestión de Inmuebles",
        "properties_description": "Gestiona el valor y las hipotecas asociadas a tus inmuebles.",
        "add_property": "Añadir Inmueble",
        "purchase_value": "Valor de Compra",
        "current_value": "Valor Actual",
        "residual_mortgage": "Hipoteca Residual",
        "no_properties": "No se han introducido inmuebles.",

        # Scheda Impostazioni - Profilo Utente
        "user_profile": "Perfil de Usuario",
        "user_profile_desc": "Edita tu información personal y contraseña.",
        "date_of_birth": "Fecha de Nacimiento",
        "tax_code": "Código Fiscal",
        "address": "Dirección",
        "change_password": "Cambiar Contraseña",
        "save_profile": "Guardar Perfil",
        "profile_saved_success": "¡Perfil guardado con éxito!",

        # Scheda Impostazioni
        "google_settings": "Configuración de Google",
        "google_settings_desc": "Conecta tu cuenta de Google para sincronizar la base de datos con Google Drive.",
        "status_connected": "Estado: Conectado",
        "status_disconnected": "Estado: No Conectado",
        "connect_google_account": "Conectar Cuenta de Google",
        "disconnect_google_account": "Desconectar Cuenta de Google",
        "sync_db_drive": "Sincronizar Base de Datos",
        "sync_db_drive_tooltip": "Subir BD local a Google Drive (sobrescribe)",
        "language_and_currency": "Idioma y Moneda",
        "language_and_currency_desc": "Elige el idioma y la moneda para la aplicación.",
        "language": "Idioma",
        "currency": "Moneda",
        "default_account": "Cuenta Predeterminada",
        "default_account_desc": "Selecciona una cuenta predeterminada para usar en nuevas transacciones.",
        "save_default_account": "Guardar Cuenta Predeterminada",
        "backup_and_restore": "Copia de Seguridad y Restauración",
        "backup_and_restore_desc": "Guarda una copia de seguridad de tus datos o restaura desde una copia anterior.",
        "create_backup": "Crear Copia de Seguridad",
        "restore_from_backup": "Restaurar desde Copia",

        #dati aggiornato da sistemare e rorganizzare es
        "subcategory": "Subcategoría",
        "category": "Categoría",
        "edit_role_for": "Editar rol para",
        "avg_purchase_price": "Precio Medio de Compra",
        "avg_purchase_price_tooltip": "Precio medio ponderado de compra de activos",
        "past_gain_loss_tooltip": "Ganancia/Pérdida total pasada (antes de ingresar al sistema)",
        "manage_shared_account": "Gestionar Cuenta Compartida",
        "debit_day_of_month": "Día del Mes",
        "select_existing_asset_optional": "Seleccionar Activo Existente (opcional)",
        "invalid_amount_or_quantity": "Importe o cantidad no válidos",
        "create_new_mortgage": "Crear Nueva Hipoteca",
        "default_payment_subcategory": "Subcategoría de Pago Predeterminada",
        "start_date": "Fecha de Inicio",
        "required_field": "Campo obligatorio",
        "delete_account": "Eliminar Cuenta",
        "auto_debit": "Débito Automático",
        "auto_debit_desc": "Selecciona si el débito debe ser ejecutado automáticamente cada mes.",
    },
    "de": {
        # Generali
        "app_title": "Familienbudget",
        "edit": "Bearbeiten",
        "delete": "Löschen",
        "save": "Speichern",
        "cancel": "Abbrechen",
        "close": "Schließen",
        "add": "Hinzufügen",
        "new_transaction": "Neue Transaktion",
        "new_transfer": "Neue Überweisung",
        "no_category": "Keine Kategorie",
        "confirm_delete_title": "Löschen bestätigen",
        "confirm_delete_content": "Möchten Sie dieses Element wirklich löschen? Diese Aktion ist unumkehrbar.",
        "yes_delete": "Ja, löschen",
        "fill_all_fields": "Bitte füllen Sie alle Pflichtfelder aus.",
        "invalid_amount": "Ungültiger Betrag.",
        "amount_not_zero": "Der Betrag darf nicht null sein.",
        "description_required": "Beschreibung ist erforderlich.",
        "error_dialog_title": "Fehler",
        "select_an_account": "Wählen Sie ein Konto aus.",

        # Schede Principali
        "my_data": "Meine Daten",
        "budget": "Budget",
        "personal_accounts": "Persönliche Konten",
        "shared_accounts": "Geteilte Konten",
        "fixed_expenses": "Fixkosten",
        "loans": "Kredite",
        "properties": "Immobilien",
        "family": "Familie",

        # Azioni AppBar
        "settings": "Einstellungen",
        "admin_panel_title": "Admin-Panel",
        "export_data": "Daten exportieren",
        "logout": "Abmelden",
        "info": "Informationen",

        # Recupero Password
        "forgot_password": "Passwort vergessen?",
        "password_recovery_title": "Passwort-Wiederherstellung",
        "password_recovery_desc": "Geben Sie Ihre E-Mail-Adresse ein, um ein temporäres Passwort zu erhalten.",
        "send_reset_link": "Temporäres Passwort senden",
        "back_to_login": "Zurück zum Login",
        "email_is_required": "E-Mail ist erforderlich.",
        "set_new_password_title": "Neues Passwort erstellen",
        "new_password": "Neues Passwort",
        "confirm_new_password": "Neues Passwort bestätigen",
        "save_new_password": "Neues Passwort speichern",
        "passwords_do_not_match": "Die Passwörter stimmen nicht überein oder sind leer.",
        "password_updated_success": "Passwort erfolgreich aktualizzato! Sie können sich jetzt anmelden.",
        "invalid_or_expired_token": "Ungültiger oder abgelaufener Token. Bitte fordern Sie einen neuen Reset an.",
        "reset_link_sent_confirmation": "Wenn ein Konto mit dieser E-Mail-Adresse verknüpft ist, wurde ein temporäres Passwort gesendet.",
        "no_account_question": "Haben Sie noch kein Konto?",
        "register_now": "Jetzt registrieren",

        # Pannello Admin
        "categories_management": "Kategorienverwaltung",
        "members_management": "Mitgliederverwaltung",
        "admin_google_settings": "Google",
        "add_category": "Kategorie hinzufügen",
        "category_name": "Kategoriename",
        "no_categories_found": "Keine Kategorien gefunden.",
        "invite_member": "Mitglied einladen",
        "username_or_email": "Benutzername oder E-Mail",
        "role": "Rolle",
        "username": "Benutzername",
        "email": "E-Mail",
        "invite": "Einladen",
        "remove_from_family": "Aus der Familie entfernen",
        "no_members_found": "Keine anderen Mitglieder in der Familie.",

        # Dialogo Transazioni
        "expense": "Ausgabe",
        "income": "Einnahme",
        "category_optional": "Kategorie (optional)",
        "shared_suffix": "(Geteilt)",
        "personal_suffix": "(Persönlich)",

        # Dialogo Conti
        "manage_account": "Konto verwalten",
        "add_account": "Konto hinzufügen",
        "edit_account": "Konto bearbeiten",
        "account_name_placeholder": "Kontoname (z.B. Hauptkonto)",
        "account_type": "Kontotyp",
        "iban_optional": "IBAN (Optional)",
        "initial_balance_optional": "Anfangssaldo (Optional)",
        "set_initial_balance": "Anfangssaldo festlegen",
        "add_initial_asset": "Anfangsvermögen hinzufügen",
        "initial_assets": "Anfangsvermögen:",
        "initial_assets_desc": "Geben Sie den aktuellen Wert und den gesamten bereits vorhandenen G/V ein (optional).",
        "ticker": "Ticker",
        "asset_name": "Anlagename",
        "quantity": "Menge",
        "current_unit_price": "Aktueller Stk.-Preis",
        "past_gain_loss": "Früherer Gesamt-G/V",
        "remove_asset": "Anlage entfernen",
        "set_as_default_account": "Als Standardkonto für Ausgaben festlegen",
        "iban_in_use_or_invalid": "IBAN wird bereits verwendet oder ist ungültig",

        # Dialogo Conti Condivisi
        "manage_shared_account_dialog": "Geteiltes Konto verwalten",
        "create_shared_account": "Geteiltes Konto erstellen",
        "edit_shared_account": "Geteiltes Konto bearbeiten",
        "shared_account_name": "Name des geteilten Kontos",
        "sharing_type": "Art der Freigabe",
        "sharing_type_family": "Ganze Familie (verwaltet von Admin)",
        "sharing_type_users": "Bestimmte Benutzer",
        "select_participants": "Teilnehmer auswählen (nur für 'Bestimmte Benutzer'):",
        "select_at_least_one_participant": "Wählen Sie mindestens einen Teilnehmer für 'Bestimmte Benutzer'-Konten aus.",

        # Dialogo Giroconto
        "new_transfer_dialog": "Neue Überweisung",
        "from_account": "Von Konto (Quelle)",
        "to_account": "Auf Konto (Ziel)",
        "transfer_description_placeholder": "Beschreibung (z.B. Gemeinsame Ausgaben)",
        "accounts_must_be_different": "Die Konten müssen unterschiedlich sein",
        "select_source_account": "Wählen Sie ein Quellkonto",
        "select_destination_account": "Wählen Sie ein Zielkonto",
        "execute_transfer": "Überweisung ausführen",

        # Dialogo Spese Fisse
        "manage_fixed_expense": "Fixkosten verwalten",
        "add_fixed_expense": "Fixkosten hinzufügen",
        "edit_fixed_expense": "Fixkosten bearbeiten",
        "expense_name_placeholder": "Ausgabenname (z.B. Netflix-Abo)",
        "debit_account": "Belastungskonto",
        "debit_day": "Tag des Monats für die Belastung",

        # Dialogo Fondo Pensione
        "manage_pension_fund_dialog": "Pensionsfondsverwaltung",
        "manage_pension_fund_for": "Verwaltung: {0}",
        "update_total_value": "Aktualisieren Sie den Gesamtwert des Fonds:",
        "current_total_value": "Aktueller Gesamtwert",
        "update_value": "Wert aktualisieren",
        "perform_operation": "Eine Operation durchführen:",
        "operation_amount": "Betrag der Operation",
        "linked_account": "Konto für Einzahlung/Auszahlung",
        "deposit_from_account": "Vom Konto einzahlen",
        "deposit_from_external": "Von extern einzahlen",
        "deposit_from_external_tooltip": "Z.B. vom Arbeitgeber",
        "withdraw_to_account": "Auf Konto abheben",
        "pension_fund_value_updated": "Pensionsfondswert aktualisiert!",
        "error_updating_value": "Fehler beim Aktualisieren.",
        "pension_fund_op_success": "Pensionsfondsoperation erfasst!",
        "pension_fund_op_error": "Fehler beim Erfassen der Operation.",

        # Dialogo Immobili
        "manage_property_dialog": "Immobilienverwaltung",
        "add_property": "Immobilie hinzufügen",
        "edit_property": "Immobilie bearbeiten",
        "property_name": "Immobilienname",
        "address": "Adresse",
        "city": "Stadt",
        "bare_ownership": "Nacktes Eigentum",
        "linked_mortgage": "Verbundene Hypothek",

        # Dialogo Portafoglio
        "manage_portfolio_dialog": "Portfolioverwaltung",
        "total_portfolio_value": "Gesamter Portfoliowert",
        "total_gain_loss": "Gesamtgewinn/-verlust",
        "add_operation": "Operation hinzufügen",
        "unit_price": "Stückpreis",
        "buy": "Kaufen",
        "sell": "Verkaufen",
        "update_price": "Preis aktualisieren",
        "new_price": "Neuer Preis",
        "edit_asset_details": "Anlagedetails bearbeiten",

        # Dialogo Prestiti
        "manage_loan_dialog": "Kreditverwaltung",
        "edit_loan": "Kredit bearbeiten",
        "loan_name": "Kreditname",
        "loan_type": "Typ",
        "interest_amount": "Zinsbetrag",
        "installment_due_day": "Fälligkeitstag der Rate",
        "default_payment_account": "Standard-Zahlungskonto",
        "default_payment_category": "Standard-Zahlungskategorie",
        "pay_installment_dialog_title": "Rate zahlen",
        "payment_amount": "Zahlungsbetrag",
        "payment_date": "Zahlungsdatum",
        "payment_account": "Zahlungskonto",
        "payment_category": "Zahlungskategorie",
        "execute_payment": "Zahlung ausführen",

        # Scheda Conti Personali
        "net_worth": "Nettovermögen",
        "liquidity": "Liquidität",
        "investments": "Anlagen",
        "my_personal_accounts": "Meine Persönlichen Konten",
        "add_personal_account": "Neues persönliches Konto hinzufügen",
        "no_personal_accounts": "Sie haben noch keine persönlichen Konten hinzugefügt.",
        "current_balance": "Aktueller Saldo",
        "value": "Wert",
        "manage_portfolio": "Portfolio Verwalten",
        "manage_pension_fund": "Pensionsfonds Verwalten",

        # Scheda Conti Condivisi
        "no_shared_accounts": "Sie sind noch keinem geteilten Konto beigetreten.",
        "shared_type_family": "Ganze Familie",
        "shared_type_users": "Bestimmte Benutzer",

        # Scheda Personale (I Miei Dati)
        "welcome_back": "Willkommen zurück, {0}!",
        "total_wealth": "Gesamtvermögen",
        "liquidity_details": "({0} an Liquidität zum {1})",
        "latest_transactions": "Letzte Transaktionen (Liquidität)",
        "filter_by_month": "Nach Monat filtern",

        # Scheda Famiglia
        "wealth_by_member": "Vermögen pro Mitglied",
        "total_family_wealth": "Gesamtvermögen der Familie",
        "total_liquidity": "Gesamtliquidität",
        "total_investments": "Gesamtanlagen",
        "all_family_transactions": "Alle Familientransaktionen",
        "user": "Benutzer",
        "date": "Datum",
        "description": "Beschreibung",
        "account": "Konto",
        "amount": "Betrag",
        "no_transactions_found_family": "Keine Transaktionen für die Familie gefunden.",
        "shared": "Geteilt",
        "no_family_access_permission": "Sie haben keine Berechtigung, diesen Bereich anzuzeigen.",
        "not_in_family": "Sie wurden noch keiner Familie hinzugefügt.",

        # Scheda Budget
        "budget_management": "Budgetverwaltung",
        "budget_description": "Legen Sie monatliche Ausgabenlimits pro Kategorie fest und überwachen Sie sie.",
        "set_budget": "Budget festlegen",
        "no_budget_set": "Kein Budget festgelegt. Klicken Sie auf '+', um zu beginnen.",
        "spent": "Ausgegeben",
        "of": "von",
        "remaining": "Verbleibend",
        "set_monthly_budget": "Monatliches Budget festlegen",
        "limit_amount": "Limitbetrag",
        "budget_saved": "Budget erfolgreich gespeichert!",

        # Scheda Spese Fisse
        "fixed_expenses_management": "Verwaltung der Fixkosten",
        "fixed_expenses_description": "Richten Sie hier Ihre wiederkehrenden Ausgaben ein (z. B. Miete, Abonnements). Sie werden jeden Monat automatisch abgebucht.",
        "name": "Name",
        "active": "Aktiv",
        "actions": "Aktionen",
        "no_fixed_expenses": "Keine Fixkosten konfiguriert.",

        # Scheda Prestiti
        "loans_management": "Kreditverwaltung",
        "loans_description": "Verfolgen Sie Hypotheken, Finanzierungen und Kredite.",
        "add_loan": "Kredit hinzufügen",
        "pay_installment": "Rate zahlen",
        "financed_amount": "Finanzierter Betrag",
        "remaining_amount": "Restbetrag",
        "monthly_installment": "Monatliche Rate",
        "total_months": "Gesamtmonate",
        "no_loans": "Keine Kredite eingegeben.",

        # Scheda Immobili
        "properties_management": "Immobilienverwaltung",
        "properties_description": "Verwalten Sie den Wert und die zugehörigen Hypotheken Ihrer Immobilien.",
        "add_property": "Immobilie hinzufügen",
        "purchase_value": "Kaufwert",
        "current_value": "Aktueller Wert",
        "residual_mortgage": "Restschuld",
        "no_properties": "Keine Immobilien eingegeben.",

        # Scheda Impostazioni - Profilo Utente
        "user_profile": "Benutzerprofil",
        "user_profile_desc": "Bearbeiten Sie Ihre persönlichen Informationen und Ihr Passwort.",
        "date_of_birth": "Geburtsdatum",
        "tax_code": "Steuernummer",
        "address": "Adresse",
        "change_password": "Passwort ändern",
        "save_profile": "Profil speichern",
        "profile_saved_success": "Profil erfolgreich gespeichert!",

        # Scheda Impostazioni
        "google_settings": "Google-Einstellungen",
        "google_settings_desc": "Verbinden Sie Ihr Google-Konto, um die Datenbank mit Google Drive zu synchronisieren.",
        "status_connected": "Status: Verbunden",
        "status_disconnected": "Status: Nicht verbunden",
        "connect_google_account": "Google-Konto verbinden",
        "disconnect_google_account": "Google-Konto trennen",
        "sync_db_drive": "Datenbank synchronisieren",
        "sync_db_drive_tooltip": "Lokale DB auf Google Drive hochladen (überschreibt)",
        "language_and_currency": "Sprache und Währung",
        "language_and_currency_desc": "Wählen Sie die Sprache und Währung für die Anwendung.",
        "language": "Sprache",
        "currency": "Währung",
        "default_account": "Standardkonto",
        "default_account_desc": "Wählen Sie ein Standardkonto für neue Transaktionen.",
        "save_default_account": "Standardkonto speichern",
        "backup_and_restore": "Sicherung und Wiederherstellung",
        "backup_and_restore_desc": "Speichern Sie eine Sicherungskopie Ihrer Daten oder stellen Sie sie aus einer früheren Sicherung wieder her.",
        "create_backup": "Datensicherung erstellen",
        "restore_from_backup": "Aus Sicherung wiederherstellen",

        #dati da sistemare e riorganizzare de
        "subcategory": "Unterkategorie",
        "category": "Kategorie",
        "edit_role_for": "Rolle bearbeiten für",
        "avg_purchase_price": "Durchschnittlicher Kaufpreis",
        "avg_purchase_price_tooltip": "Gewichteter durchschnittlicher Kaufpreis der Vermögenswerte",
        "past_gain_loss_tooltip": "Gesamter vergangener Gewinn/Verlust (vor Eingabe ins System)",
        "manage_shared_account": "Gemeinsames Konto verwalten",
        "debit_day_of_month": "Tag des Monats",
        "select_existing_asset_optional": "Vorhandenen Vermögenswert auswählen (optional)",
        "invalid_amount_or_quantity": "Ungültiger Betrag oder Menge",
        "create_new_mortgage": "Neue Hypothek erstellen",
        "default_payment_subcategory": "Standard-Zahlungsunterkategorie",
        "start_date": "Startdatum",
        "required_field": "Pflichtfeld",
        "delete_account": "Konto löschen",
        "auto_debit": "Automatische Abbuchung",
        "auto_debit_desc": "Wählen Sie aus, ob die Abbuchung automatisch jeden Monat ausgeführt werden soll.",
    },
}

CURRENCIES = {
    "EUR": {"symbol": "€", "format": "{amount:.2f} {symbol}"},
    "USD": {"symbol": "$", "format": "{symbol}{amount:.2f}"},
    "GBP": {"symbol": "£", "format": "{symbol}{amount:.2f}"},

}

class LocalizationManager:
    def __init__(self, default_lang="it", default_currency="EUR"):
        self.language = default_lang
        self.currency = default_currency
        self.strings = STRINGS
        self.currencies = CURRENCIES

    def set_language(self, lang_code):
        """Imposta la lingua corrente."""
        if lang_code in self.strings:
            self.language = lang_code
            print(f"Lingua impostata su: {lang_code}")
        else:
            print(f"Attenzione: lingua '{lang_code}' non trovata. Uso il default '{self.language}'.")

    def set_currency(self, currency_code):
        """Imposta la valuta corrente."""
        if currency_code in self.currencies:
            self.currency = currency_code
            print(f"Valuta impostata su: {currency_code}")
        else:
            print(f"Attenzione: valuta '{currency_code}' non trovata. Uso il default '{self.currency}'.")

    def get(self, key, *args):
        """
        Recupera una stringa tradotta per una data chiave.
        Se la chiave non esiste, restituisce la chiave stessa.
        """
        try:
            translated_string = self.strings[self.language].get(key, key)
            if args:
                return translated_string.format(*args)
            return translated_string
        except KeyError:
            # Fallback sulla lingua di default se la lingua corrente non esiste
            return self.strings.get(self.language, {}).get(key, key)

    def format_currency(self, amount):
        """Formatta un importo numerico con il simbolo e il formato della valuta corrente."""
        currency_info = self.currencies.get(self.currency, self.currencies["EUR"])
        return currency_info["format"].format(amount=amount, symbol=currency_info["symbol"])