# Missing translation keys for the BudgetAmico application
# This file lists keys that need to be added to utils/localization.py
# Each language dictionary contains the proper translations for all supported languages.

MISSING_STRINGS = {
    "it": {

        "manage_shared_account": "Gestisci Conto Condiviso",
        "debit_day_of_month": "Giorno del Mese",
        "select_existing_asset_optional": "Seleziona Asset Esistente (opzionale)",
        "invalid_amount_or_quantity": "Importo o quantità non validi",
        "create_new_mortgage": "Crea Nuovo Mutuo",
        "default_payment_subcategory": "Sottocategoria Pagamento Predefinita",
        "start_date": "Data Inizio",
        "required_field": "Campo obbligatorio",
        "delete_account": "Elimina Conto",
    },
    "en": {
        "subcategory": "Subcategory",
        "category": "Category",
        "edit_role_for": "Edit role for",
        "avg_purchase_price": "Average Purchase Price",
        "avg_purchase_price_tooltip": "Weighted average purchase price of assets",
        "past_gain_loss_tooltip": "Total past Gain/Loss (before entering the system)",
        "manage_shared_account": "Manage Shared Account",
        "debit_day_of_month": "Day of the Month",
        "select_existing_asset_optional": "Select Existing Asset (optional)",
        "invalid_amount_or_quantity": "Invalid amount or quantity",
        "create_new_mortgage": "Create New Mortgage",
        "default_payment_subcategory": "Default Payment Subcategory",
        "start_date": "Start Date",
        "required_field": "Required field",
        "delete_account": "Delete Account",
    },
    "es": {
        "subcategory": "Subcategoría",
        "category": "Categoría",
        "edit_role_for": "Editar rol para",
        "avg_purchase_price": "Precio Medio de Compra",
        "avg_purchase_price_tooltip": "Precio medio ponderado de compra de activos",
        "past_gain_loss_tooltip": "Ganancia/Pérdida total pasada (antes de ingresar al sistema)",
        "manage_shared_account": "Gestionar Cuenta Compartida",
        "debit_day_of_month": "Día del Mes",
        "select_existing_asset_optional": "Seleccionar Activo Existente (opcional)",
        "invalid_amount_or_quantity": "Importe o cantidad no válidos",
        "create_new_mortgage": "Crear Nueva Hipoteca",
        "default_payment_subcategory": "Subcategoría de Pago Predeterminada",
        "start_date": "Fecha de Inicio",
        "required_field": "Campo obligatorio",
        "delete_account": "Eliminar Cuenta",
    },
    "de": {
        "subcategory": "Unterkategorie",
        "category": "Kategorie",
        "edit_role_for": "Rolle bearbeiten für",
        "avg_purchase_price": "Durchschnittlicher Kaufpreis",
        "avg_purchase_price_tooltip": "Gewichteter durchschnittlicher Kaufpreis der Vermögenswerte",
        "past_gain_loss_tooltip": "Gesamter vergangener Gewinn/Verlust (vor Eingabe ins System)",
        "manage_shared_account": "Gemeinsames Konto verwalten",
        "debit_day_of_month": "Tag des Monats",
        "select_existing_asset_optional": "Vorhandenen Vermögenswert auswählen (optional)",
        "invalid_amount_or_quantity": "Ungültiger Betrag oder Menge",
        "create_new_mortgage": "Neue Hypothek erstellen",
        "default_payment_subcategory": "Standard-Zahlungsunterkategorie",
        "start_date": "Startdatum",
        "required_field": "Pflichtfeld",
        "delete_account": "Konto löschen",
    },
}
